[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "polars-jsonschema-bridge"
version.workspace = true

[dependencies]
polars.workspace = true
# serde = { features = ["derive"], workspace = true }
serde_json.workspace = true
thiserror = "2.0.15"
