[package]
name = "polars-jsonschema-bridge"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
polars.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror = "2.0.15"
