[package]
authors.workspace = true
description = "Conversion between JSON Schema and Polars Schema"
edition.workspace = true
license.workspace = true
name = "polars-jsonschema-bridge"
version = "0.1.0"

[dependencies]
polars.workspace = true
serde_json.workspace = true
