[dependencies]
genson-core = { path = "../genson-core" }
serde_json = { workspace = true }

[package]
authors = ["Louis Maddox <louismmx@gmail.com>"]
description = "Command-line interface for JSON schema inference"
edition = "2021"
license = "MIT"
name = "genson-cli"
version = "0.1.0"

[dev-dependencies]
assert_cmd = { features = ["color", "color-auto"], version = "2.0.17" }
predicates = "3.1.3"
tempfile = "3"
